version: "3.8"
services:
  todo_mysql:
    container_name: todo_mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=my_secret_root_pw
      - MYSQL_DATABASE=todo_db
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql

  todo_server:
    container_name: todo_server
    build:
      context: .
      dockerfile: server.dockerfile
    depends_on:
      - todo_mysql
    ports:
      - 5555:5555
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./:/app

volumes:
  data:
